apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: monitoring
spec:
  vaultConnectionRef: vault-secrets-operator/default
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: vso-admin
    serviceAccount: vault-auth
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: grafana-admin-credentials
spec:
  vaultAuthRef: monitoring
  mount: kv
  type: kv-v2
  path: infra/monitoring/grafana
  refreshAfter: 1m
  hmacSecretData: true
  destination:
    create: true
    overwrite: true
    name: grafana-admin-credentials
    type: Opaque
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: pagerduty-integration-key
spec:
  vaultAuthRef: monitoring
  mount: kv
  type: kv-v2
  path: infra/monitoring/pagerduty
  refreshAfter: 1m
  hmacSecretData: true
  destination:
    create: true
    overwrite: true
    name: pagerduty-integration-key
    type: Opaque
