apiVersion: v1
kind: Namespace
metadata:
  name: security-trivy
  labels:
    app.kubernetes.io/part-of: security-tools
    platform.example/managed-by: argocd
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
