apiVersion: v1
kind: ResourceQuota
metadata:
  name: security-trivy
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "3"
    limits.memory: 3Gi
    requests.storage: 2Gi
    persistentvolumeclaims: "1"
    count/jobs.batch: "5"
    count/cronjobs.batch: "2"
