apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra-security
  namespace: argocd
spec:
  description: Cluster infrastructure, observability, and security services
  sourceRepos:
    - https://github.com/EmrhT/ultimate-iac.git
    - https://github.com/kubernetes-sigs/gateway-api.git
    - https://charts.jetstack.io
    - https://metallb.github.io/metallb
    - https://charts.longhorn.io
    - https://kubernetes-sigs.github.io/metrics-server
    - https://traefik.github.io/charts
    - https://helm.releases.hashicorp.com
    - https://codecentric.github.io/helm-charts
    - https://prometheus-community.github.io/helm-charts
    - https://falcosecurity.github.io/charts
    - https://helm.elastic.co
    - https://SonarSource.github.io/helm-chart-sonarqube
    - https://aquasecurity.github.io/helm-charts
    - https://raw.githubusercontent.com/DefectDojo/django-DefectDojo/helm-charts
    - https://kyverno.github.io/kyverno/
    - https://jertel.github.io/elastalert2/
  destinations:
    - server: https://kubernetes.default.svc
      namespace: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
