apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security-sonarqube
resources:
  - namespace.yaml
  - postgresql.yaml
  - scanner-cronjob.yaml
  - httproute.yaml
  - resourcequota.yaml
  - podmonitor.yaml
  - prometheusrule.yaml
  - vault-secrets.yaml
