apiVersion: v1
kind: ResourceQuota
metadata:
  name: security-sonarqube
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "5"
    limits.memory: 6Gi
    requests.storage: 1536Mi
    persistentvolumeclaims: "2"
    count/jobs.batch: "5"
    count/cronjobs.batch: "2"
