apiVersion: v1
kind: ServiceAccount
metadata:
  name: security-sonarqube-postgresql
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: security-sonarqube-scan
automountServiceAccountToken: false
