apiVersion: v1
kind: ServiceAccount
metadata:
  name: security-sonarqube-postgresql
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: security-sonarqube-scan
automountServiceAccountToken: false
