providers:
  kubernetesCRD:
    enabled: false
  kubernetesIngress:
    enabled: false
  kubernetesGateway:
    enabled: true
ingressClass:
  enabled: false
gatewayClass:
  enabled: true
  name: traefik
gateway:
  enabled: true
  name: traefik
  listeners:
    web:
      port: 8000
      protocol: HTTP
      namespacePolicy:
        from: All
    websecure:
      port: 8443
      protocol: HTTPS
      namespacePolicy:
        from: All
      certificateRefs:
        - group: ""
          kind: Secret
          name: no-name-win-wildcard-tls
      mode: Terminate
ingressRoute:
  dashboard:
    enabled: false
api:
  dashboard: true
  insecure: false
ports:
  web:
    expose:
      default: true
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
service:
  spec:
    type: LoadBalancer
    loadBalancerIP: 192.168.122.120
log:
  level: INFO
accessLog:
  enabled: true
  format: json
metrics:
  prometheus:
    service:
      enabled: true
    serviceMonitor:
      enabled: true
