apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../environments/dev
images:
  - name: ghcr.io/emrht/podinfo-emrah
    newName: ghcr.io/emrht/podinfo-emrah
    digest: sha256:95c534699e3a2626ccbf45a1ab802dbc16287655344d8a2b7e62a59b7865ec5d
labels:
  - pairs:
      platform.example/cluster: lab-a
    includeTemplates: true
patches:
  - target:
      group: gateway.networking.k8s.io
      version: v1
      kind: HTTPRoute
      name: podinfo
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: podinfo-lab-a-dev.no-name.win
      - op: add
        path: /spec/hostnames/-
        value: ci-podinfo-lab-a-dev.no-name.win
