apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../environments/dev
images:
  - name: ghcr.io/emrht/podinfo-emrah
    newName: ghcr.io/emrht/podinfo-emrah
    digest: sha256:0ef01cdb13b3fcd0ab57b7428e790b0d632dfc89e767e3e055d8da6b39dc7c89
labels:
  - pairs:
      platform.example/cluster: lab-a
    includeTemplates: true
patches:
  - target:
      group: gateway.networking.k8s.io
      version: v1
      kind: HTTPRoute
      name: podinfo
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: podinfo-lab-a-dev.no-name.win
      - op: add
        path: /spec/hostnames/-
        value: ci-podinfo-lab-a-dev.no-name.win
