apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: podinfo
spec:
  vaultAuthRef: podinfo
  mount: kv
  type: kv-v2
  path: dev/podinfo
  refreshAfter: 1m
  hmacSecretData: true
  destination:
    create: true
    overwrite: true
    name: podinfo-vault
    type: Opaque
  rolloutRestartTargets:
    - kind: Deployment
      name: podinfo
