apiVersion: v1
kind: ServiceAccount
metadata:
  name: security-kube-bench-control-plane
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: security-kube-bench-workers
automountServiceAccountToken: false
