apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: cloudflared
spec:
  vaultConnectionRef: vault-secrets-operator/default
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: vso-admin
    serviceAccount: vault-auth
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cloudflared-token
spec:
  vaultAuthRef: cloudflared
  mount: kv
  type: kv-v2
  path: infra/cloudflare/tunnel
  refreshAfter: 1m
  hmacSecretData: true
  destination:
    create: true
    overwrite: true
    name: cloudflared-token
    type: Opaque
  rolloutRestartTargets:
    - kind: Deployment
      name: cloudflared
