---
all:
  hosts:
    platform-dev-cp-01:
      ansible_host: 192.168.122.31
      ip: 192.168.122.31
      access_ip: 192.168.122.31
    platform-dev-worker-01:
      ansible_host: 192.168.122.41
      ip: 192.168.122.41
      access_ip: 192.168.122.41
    platform-dev-worker-02:
      ansible_host: 192.168.122.42
      ip: 192.168.122.42
      access_ip: 192.168.122.42
    platform-dev-worker-03:
      ansible_host: 192.168.122.43
      ip: 192.168.122.43
      access_ip: 192.168.122.43
  children:
    kube_control_plane:
      hosts:
        platform-dev-cp-01: {}
    kube_node:
      hosts:
        platform-dev-worker-01: {}
        platform-dev-worker-02: {}
        platform-dev-worker-03: {}
    etcd:
      hosts:
        platform-dev-cp-01: {}
    k8s_cluster:
      children:
        kube_control_plane: {}
        kube_node: {}

