apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: falco
resources:
  - service-account.yaml
  - rbac.yaml
  - configmap.yaml
  - service.yaml
  - deployment.yaml
labels:
  - pairs:
      app.kubernetes.io/name: falco-talon
      app.kubernetes.io/component: runtime-response
      app.kubernetes.io/part-of: falco
      app.kubernetes.io/managed-by: argocd
      owner: platform
    includeSelectors: false
