apiVersion: v1
kind: Service
metadata:
  name: falco-talon
spec:
  selector:
    app.kubernetes.io/name: falco-talon
  ports:
    - name: http
      port: 2803
      targetPort: http
      protocol: TCP
