apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security-zap
resources:
  - namespace.yaml
  - vault-secrets.yaml
  - automation-plan.yaml
  - deployment.yaml
  - service.yaml
  - httproute-ci.yaml
  - resourcequota.yaml
