apiVersion: v1
kind: ResourceQuota
metadata:
  name: security-zap
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "2"
    limits.memory: 3Gi
    requests.ephemeral-storage: 2Gi
    limits.ephemeral-storage: 4Gi
    count/pods: "2"
