apiVersion: v1
kind: ResourceQuota
metadata:
  name: security-zap
spec:
  hard:
    requests.cpu: 250m
    requests.memory: 768Mi
    limits.cpu: "1"
    limits.memory: 1536Mi
    requests.ephemeral-storage: 512Mi
    limits.ephemeral-storage: 2Gi
    count/pods: "2"
