apiVersion: v1
kind: ResourceQuota
metadata:
  name: security-zap
spec:
  hard:
    requests.cpu: 500m
    requests.memory: 2Gi
    limits.cpu: "2"
    limits.memory: 4Gi
    requests.ephemeral-storage: 512Mi
    limits.ephemeral-storage: 2Gi
    count/pods: "2"
