apiVersion: v1
kind: ServiceAccount
metadata:
  name: security-kyverno-defectdojo
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: security-kyverno-defectdojo-report-reader
rules:
  - apiGroups:
      - openreports.io
    resources:
      - reports
      - clusterreports
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: security-kyverno-defectdojo-report-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: security-kyverno-defectdojo-report-reader
subjects:
  - kind: ServiceAccount
    name: security-kyverno-defectdojo
    namespace: kyverno
