apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: falco-defectdojo
  annotations:
    argocd.argoproj.io/sync-wave: "-29"
spec:
  vaultConnectionRef: vault-secrets-operator/default
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: vso-admin
    serviceAccount: vault-auth
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: falco-defectdojo-credentials
  annotations:
    argocd.argoproj.io/sync-wave: "-28"
spec:
  vaultAuthRef: falco-defectdojo
  mount: kv
  type: kv-v2
  path: security/defectdojo/credentials
  refreshAfter: 1m
  hmacSecretData: true
  destination:
    create: true
    overwrite: true
    name: security-falco-defectdojo
    type: Opaque
    transformation:
      excludeRaw: true
      excludes:
        - '.*'
      templates:
        api-token:
          text: '{{ get .Secrets "defectdojo-api-token" }}'

