persistence:
  defaultClass: true
  defaultClassReplicaCount: 2
defaultSettings:
  defaultDataPath: /var/lib/longhorn
  defaultReplicaCount: 2
  replicaSoftAntiAffinity: false
  storageMinimalAvailablePercentage: 15
  removeSnapshotsDuringFilesystemTrim: true
longhornUI:
  replicas: 1
