driver:
  kind: modern_ebpf
falco:
  json_output: true
  json_include_output_property: true
  http_output:
    enabled: false
tty: false
serviceMonitor:
  create: true
  interval: 60s
falcosidekick:
  enabled: false
