apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: platform
spec:
  version: 9.4.2
  image: docker.elastic.co/kibana/kibana@sha256:b9749a7672939d1a96dd9c99b86fd84634aab8d03b0889f02177d881aea3eb01
  count: 1
  elasticsearchRef:
    name: platform
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  podTemplate:
    spec:
      serviceAccountName: platform-kibana
      automountServiceAccountToken: false
      containers:
        - name: kibana
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              memory: 1Gi
