apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: platform
spec:
  version: 9.4.2
  count: 1
  elasticsearchRef:
    name: platform
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  podTemplate:
    spec:
      serviceAccountName: platform-kibana
      automountServiceAccountToken: false
      containers:
        - name: kibana
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              memory: 1Gi
