apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-elasticsearch
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-kibana
automountServiceAccountToken: false
