apiVersion: v1
kind: ResourceQuota
metadata:
  name: network-testing
spec:
  hard:
    requests.cpu: 100m
    requests.memory: 128Mi
    limits.cpu: 500m
    limits.memory: 512Mi
    requests.ephemeral-storage: 128Mi
    limits.ephemeral-storage: 512Mi
    count/pods: "2"
