apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../environments/prod
images:
  - name: ghcr.io/emrht/podinfo-emrah
    newName: ghcr.io/emrht/podinfo-emrah
    digest: sha256:b2153adb4718adcc661378e6cdda57c14a20a9f4b150d64539752b9abc0405f7
labels:
  - pairs:
      platform.example/cluster: lab-a
    includeTemplates: true
patches:
  - target:
      group: gateway.networking.k8s.io
      version: v1
      kind: HTTPRoute
      name: podinfo
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: podinfo-lab-a-prod.no-name.win
