apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../environments/prod
images:
  - name: ghcr.io/emrht/podinfo-emrah
    newName: ghcr.io/emrht/podinfo-emrah
    digest: sha256:abd24f9d0f8237982fb1788f1b7e99d5c361c0a691bf67d0295d3c72dd0ac9ad
labels:
  - pairs:
      platform.example/cluster: lab-a
    includeTemplates: true
patches:
  - target:
      group: gateway.networking.k8s.io
      version: v1
      kind: HTTPRoute
      name: podinfo
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: podinfo-lab-a-prod.no-name.win
