apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - filesystem-trim.yaml
  - prometheus-daily-snapshot.yaml
  - prometheus-daily-snapshot-delete.yaml
  - prometheus-daily-trim.yaml
  - vault-daily-snapshot.yaml
